### ISSUE TITLE
Have you enabled Android hardware acceleration in the new app?

### ISSUE THREAD

**Issue by Greenheart** [29ki/29k#1020]
### What brings you here and how are you?

I'm doing well and I want to share an idea. I'm pretty excited about it given the results I saw in another RN app after making this change.

### Summary

I saw a significant speed-up of the other RN app I'm developing, which made a huge difference in how it felt when interacting with the app. Hopefully this can have the same effect for 29k.

### Motivation

The current 29k app is pretty fast and simple, but I know there will be more features and content added to it which might affect performance.

By adding explicit hardware acceleration with `android:hardwareAccelerated="true"` to the `client/android/app/main/AndroidManifest.xml` file , performance was greatly improved in another RN app I'm developing.

[According to the documentation](https://developer.android.com/topic/performance/hardware-accel), it should be enabled by default for modern apps, but since it can be turned off by each `activitiy` in the `AndroidManifest.xml`, we perhaps needed to override it to make it work.

This could be a simple way to boost performance, and make the app feel more snappy. Hardware acceleration should also save battery in for example video calls or other heavy tasks.

### Describe alternatives you've considered

Instead of enabling explicitly for the entire app, this could also be done for the activities that need it.

**Comment by gewfy** [comment]
Nice! Thanks for the tips! Should we try this in #1016 @Nipher?
