### ISSUE TITLE
Deprecated ViewPropTypes warning

### ISSUE THREAD

**Issue by Nipher** [29ki/29k#104]
### What brings you here and how are you?

Noticing that I've been very impatient and not present/in the moment, too much worries and frustrations about things out of my reach.

Noticed this issue while working on new app functionalities.

### Description

Deprecated `ViewPropTypes`, seems like some project dependency uses that, I couldn't identify which one yet.
Maybe there's a new version that doesn't use the deprecated type which we could update to.

### Steps to Reproduce

1. Run the app on your emulator or phone
2. And see if the warning shows up as on the screenshot below

<img src="https://user-images.githubusercontent.com/7523828/182118778-9e78e00f-1dcd-42bb-9377-aa620e4aac5f.png" width=300/>

**Expected behavior:**

To have a "clean" app, without any warnings like that.

**Actual behavior:**

Warning show sup right away when opening the app with unclear origin.

**Reproduces how often:**

100%

### Versions

[0893f5f](https://github.com/29ki/29k/commit/0893f5f8c342acb7c46471f0a5cca74953bd536d)

(android and ios)

**Comment by gewfy** [comment]
React Native Video issue. Is resolved in version 6, but still in alpha and way to unstable unfortunately.

**Comment by gewfy** [comment]
This warning is ignored in #153 https://github.com/29ki/29k/pull/153/files#diff-2d2b25cf7efd4cfcb855751a72bb82399e637df1582ab4e9fe7dd7a3d8238b35R14

Closing for now
