### ISSUE TITLE
Internal state invariant broken: no user with ID: <user-id>

### ISSUE THREAD

**Issue by Nipher** [29ki/29k#116]
### Description

After getting an anonymous sign in user id, which works fine at first, seems like after a day or some period of time the id isn't valid anymore.

### Steps to Reproduce

1. Run the app in dev mode with firebase/auth emulators and get a valid user id
2. wait for 24h
3. Run again and go into the "call room"

You'll get the error `Internal state invariant broken: no user with ID: <user-id>` in the console after calling the `/call` function

Maybe we should reset the user id in such dev use-case and re-do the auth?

Instead we get stuck in an invalid user-id, triggering such error.

**Reproduces how often:**

Happened twice, hard to say the exact reproducibility %

### Versions

Happened in `ios` emulator for me but I think same would occur in `android`.
 [0893f5f](https://github.com/29ki/29k/commit/0893f5f8c342acb7c46471f0a5cca74953bd536d)

**Comment by gewfy** [comment]
Did you restart the Firebase emulator in-between? Firebase emulator always starts clean, so every time you restart it the created users will be gone.

**Comment by Nipher** [comment]
May be, although I remember not always getting that error triggered when restarting functions.

Anyhow, I was wondering about the expected behavior, that's why I was wondering about:
> Maybe we should reset the user id in such dev use-case and re-do the auth?
 Instead we get stuck in an invalid user-id, triggering such error.

**Comment by Nipher** [comment]
We implemented a logout button for now which causes to "reload" the authentication by logging out and signing in anonymously again.
