### ISSUE TITLE
Firbease functions doesn't load `.env`

### ISSUE THREAD

**Issue by Nipher** [29ki/29k#156]
### What brings you here and how are you?

While coding with 29k friends we found something
and I feel okay, glad that we have a way around the issue for now.

### Description

Firbease functions doesn't seem to be loading `.env` like it is said it would on the [docs webpage](https://firebase.google.com/docs/functions/config-env).

For now, we are using `dotenv` as a dependency ourselves and importing it to load them, which should be unnecessary according to the doc linked above.

Expected behavior:

When running `yarn start` in `functions`we expect our `.env` values to be loaded.

Actual behavior:

We don't get the values loaded into `process.env`.

Reproduces how often:

Everytime when running `yarn start`

**Comment by gewfy** [comment]
Validated that process.env do get populated during runtime but not at deploy or even bootstrap.

Seems to be a known issue:
https://github.com/firebase/firebase-functions/issues/1065
https://github.com/firebase/firebase-functions/issues/1044
https://github.com/firebase/firebase-tools/issues/4656

So let's shim it with dotenv, closing it with this pull
https://github.com/29ki/29k/pull/159
