### ISSUE TITLE
Temple Content Controls and State Interfaces

### ISSUE THREAD

**Issue by transient-jonas** [29ki/29k#246]
### What brings you here and how are you?

Heyyyy folllllks, I feel good, looking forward to meet some friends later and happy to see the app coming alive!
I've had a chat with @gewfy  and @kajsaunge about the "temple experience" and content controls, so I'm creating this so we don't forget to address it.

### Summary

So, right now we have a few things that would be good to give some love to:

- The temple database document (what is it? what it contains?)
- The content and the controls / state interfaces available for each step/page of the content (for example, "prev step", "next step", "play", "pause", etc)

### Motivation

Right now we put every state on the root of the temple document, which can cause a lot of confusion and mix abstractions up and where/when they should be applied in the user experience.

### Describe alternatives you've considered

We will explore alternatives together here hopefully.

The example below shows such document at the moment
index = the current "content page" that the sharing is on
active = if `true` the content is rendered to the sharing participants, if `false` if it's only video call (no content)
playing = if `true` the current "content page" checks if there's something to be played and plays it, if `false` it pauses it.

<img width="657" alt="Screenshot 2022-09-02 at 13 55 20" src="https://user-images.githubusercontent.com/7523828/188137642-297a8ddd-1045-4340-8224-8c16cfddae38.png">

**Comment by gewfy** [comment]
This one is done!
