### ISSUE TITLE
Markdown are not extended with ours

### ISSUE THREAD

**Issue by transient-jonas** [29ki/29k#247]
### What brings you here and how are you?

Yooo hope all is well,
we tried to render some markdown recently and noticed the our styles are not used by it, feeling well!

### Description

So try rendering some markdown and see the differences between our own components and markdown.

This is the markdown library we use and [its docs](https://github.com/iamacup/react-native-markdown-display#rules-and-styles)

### Steps to Reproduce

1. Use markdown component
2. Check how it renders
3. Compare it with manually rendering the component

**Expected behavior:**

Markdown rendered components should equal our own defined styles.

**Actual behavior:**

Markdown doesn't use our styles

**Reproduces how often:**

always?

**Comment by harishfalco** [comment]
Greetings, @Nipher  I'm new to contributing to open-source, I'd want to fix this problem. Give it to me, if possible.

**Comment by gewfy** [comment]
Hi @harishfalco! So nice that you've found your way here 😃 

In our `Markdown` component...
https://github.com/29ki/29k/blob/main/client/src/common/components/Typography/Markdown/Markdown.tsx#L1-L12

... It is currently not possible to override the different styles, like so:
```javascript
<Markdown style={{ heading1: { textAlign: 'center' } }}># Heading 1</Markdown>
```

This would be a nice addition. Would you be up for fixing that?

**Comment by gewfy** [comment]
Not applicable anymore
