### ISSUE TITLE
Default scroll for journey tab is wrong on android

### ISSUE THREAD

**Issue by Greenheart** [29ki/29k#2680]
### Description

Default scroll for journey tab is wrong on android

<img src="https://github.com/29ki/29k/assets/6125097/9d9e842d-0b14-432d-9ae7-f43f883f506f" width="300" />

### Steps to Reproduce

1. Open android app
2. Go to journey tab

Or alternatively,
1. When already on journey tab, scroll down a bit on the page.
2. Pull to refresh, and notice how the default scroll is wrong.

**Expected behavior:**

There should be enough space between the header and the first conpleted session.

**Actual behavior:**

The first item is cropped.

**Reproduces how often:**

100% with both ways to reproduce it

### Versions

Version 2.25.0-v1279/P@028f3373

### Additional Information

Android

**Comment by transient-jonas** [comment]
It is designed intentionally for the filters to be centered in the screen, 
Not really if this side-effect is an issue but definitely a worth considering

Will ask @kapostints and @Lisa29k about it

**Comment by gewfy** [comment]
Interesting that you perceive it as wrong @Greenheart . It just defaults to scrolling to the position in-between your future and your past.
