### ISSUE TITLE
Android: content cut off for sessions with long titles

### ISSUE THREAD

**Issue by Greenheart** [29ki/29k#2685]
### What brings you here and how are you?

Android: content cut off for sessions with long titles

<img src="https://github.com/29ki/29k/assets/6125097/76e2aaec-1c18-43f9-bea9-79dfc5d56119" width="300" />

**Comment by transient-jonas** [comment]
I don't seem to be able to reproduce, would it be ok sharing which phone it is being used?

**Comment by transient-jonas** [comment]
Managed to reproduce on the emulator, no need to specify the phone anymore 👌 🙏

**Comment by transient-jonas** [comment]
#2687 is about to fix this

**Comment by swemail** [comment]
fixed in #2687
