### ISSUE TITLE
[Critical bug] [Android]: No links are not opening correctly in the "About aware" modal

### ISSUE THREAD

**Issue by Greenheart** [29ki/29k#2763]
### What brings you here and how are you?

Feeling pretty good!

### Description

Here's something I've experienced for the past few months, but haven't reported until now. I initially thought it was just a placeholder for things to be added later. But this seems to be an actual bug.

In the "About Aware" modal, actions that open another modal works as expected. However none of the external links work as expected. Pressing them makes nothing happen.

### Steps to Reproduce

1. Open the "about aware" modal on Android
2. Press any of the actions that should open external links (for example)

**Expected behavior:**

- External links should open properly (either in a webview or in the browser).
- Actions that open other modals (for example safety toolkit) should work too.

**Actual behavior:**

- For links, nothing happens.
- For actions opening other modals (for example safety toolkit), it works as expected.

**Reproduces how often:**

Always.

### Versions

`2.27.0-v1311/P@6e41d45`

### Additional Information

Android 11.

**Comment by gewfy** [comment]
Fix on the way! Thanks for reporting 🤗

**Comment by Greenheart** [comment]
Thank you! Keep it up! 🌅
