### ISSUE TITLE
Crash when trying to join a session

### ISSUE THREAD

**Issue by Moini** [29ki/29k#5630]
### What brings you here and how are you?

I'm a bit disappointed, tbh ... Hurried to be able to finally join a session. But all I get is a crash.

### Description

Trying to join a session without allowing Aware to record audio causes an instant crash.

### Steps to Reproduce

1. Open app
2. Join session button
3. No camera, no audio permission
4. Click join
5. App closes

**Expected behavior:**

App doesn't close. It didn't require those permissions to work before, so this is unexpected. It might also not work even with those permissions given, but I won't try.

Edit: Actually, I did try with audio permission (temporarily). But it still crashes instantly.

**Actual behavior:**

Crash

**Reproduces how often:**

Always.

### Versions

"You can get this information from your app's profile page or if it is an unreleased version you can reference the latest commit hash you're on." - Nope. But when I close the profile, for some reason, I'm on the 'About' page. There it is, at the very bottom.

2.54.0-v2464/P@75cb3767

### Additional Information

LineageOS, on Android 9...

**Comment by Moini** [comment]
(btw. the app is really really slow... seems it contains a lot of bloat? When I start it, it takes about 5 seconds to show anything but a blank screen, and then after 8 seconds or later, there's finally some contents there. It's also hard to navigate....)

**Comment by gewfy** [comment]
Totally get your disappointment! I'll look into your issues asap. However we don't have a phone running LineageOS, so a bit hard to debug at the moment. May I ask what phone model you have?

And thanks for reporting, we really appreciate you reaching out ☺️

**Comment by gewfy** [comment]
Found the reason to why it's crashing. Will fix it in the coming days.

Note to self: [crash](https://29k-international-ab.sentry.io/issues/5005121912/?environment=production&project=6617535&query=os%3A%22Android+9%22&referrer=issue-stream&statsPeriod=90d&stream_index=4), [fix](https://github.com/facebook/react-native/pull/39715)

**Comment by Moini** [comment]
Nice, @gewfy - thanks!

**Comment by gewfy** [comment]
Hi again! We just released `2.55.0` with a potential fix to your issue. It would be very helpful if you could test it by creating a "session with friends" and then just join it on your own.

And please let me know if the app feels a little less sluggish too :)

**Comment by Moini** [comment]
@gewfy Hi - thank you, it appears the crash is resolved. 

I'm not sure about the sluggishness, tbh. - a little bit, perhaps? It's very difficult to say, as I don't have a direct comparison. I noticed some flickering in the pull-up dialogs, but that may already have existed before, it's not too bad, either. Btw. the changelog didn't say anything about a crash fix.

**Comment by gewfy** [comment]
Thanks for testing it and great to hear that it works! 

This crash only happened to you and four others in the past 6 months - that's why I didn't include it in the release notes :)
