### ISSUE TITLE
Add tasteful emojis to the CMS for 👌 contributor UX

### ISSUE THREAD

**Issue by Greenheart** [29ki/29k#878]
### What brings you here and how are you?

Excitement!

### Summary

Make the CMS fun to use by adding tasteful emojis.

### Motivation

Why? Because we can 🤷‍♂️

### Describe alternatives you've considered

Doing nothing, and losing sleep due to the lack of fun 😴

### Additional context

Here's what happened when emojis decided to contribute to the https://github.com/Greenheart/idg.tools project. And oh let me tell you, this could be game changing for 29k too! 😄 

![image](https://user-images.githubusercontent.com/6125097/200050962-f6f3c43f-fbdf-45c9-9fe7-f90e3d84b43a.png)

I hope you like it, because I'm just about to launch my new startup that will help open source projects make their Netlify CMS UI:s a little bit more fun to use! It will likely be a huge success given how many 💸💸💸💸💸 emojis GitHub lets me type here!

**Comment by gewfy** [comment]
@Greenheart Love it!

I guess you've seen that Netlify CMS seems dead? https://github.com/netlify/netlify-cms/discussions/6503
Do you have a plan or consider alternatives? 

There's a very promising fork that we're keeping our eyes on and will probably contribute to https://github.com/StaticJsCMS/static-cms

**Comment by Greenheart** [comment]
Haha! Glad you liked it! I had a lot of fun as you might have noticed 😂  

Oh yeah, I've been watching the Netlify CMS situation closely since April/May. Even spoke to Netlify at a conference but didn't get any good answers.

Really exciting to see StaticCMS though - I've followed that project since it was first announced. I'm going to try it out when it's released give feedback and contribute if time allows. I'm mostly worried about the auth setup to allow contributors to sign in with their GitHub accounts to get forks and PRs automatically created for them. Not sure how that will work with the new version.
